# Generated by Django 3.1.7 on 2021-10-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=1, verbose_name='url tkiner'),
            preserve_default=False,
        ),
    ]
