# Generated by Django 3.1.7 on 2021-10-08 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
