# Generated by Django 3.1.7 on 2021-10-08 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
