# Generated by Django 3.1.7 on 2021-10-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='url_name',
        ),
    ]
