# Generated by Django 3.1.7 on 2021-10-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20211008_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url_name',
        ),
    ]
